### PR TITLE
assignment5 bz866

### PR DESCRIPTION
**Pull request by bz866**

### CODE REVIEW

**Comment by ds-ga-1007** [comment]
I am just letting you know that your repo has conflicts.
Conflicting files: adventure/tests/test_walks.py

**Comment by ds-ga-1007** [comment]
I am just letting you know that your repo has conflicts.
Conflicting files: adventure/advent

**Comment by bz866** [comment]
I have changed my file and pushed it again. Could you help me to check it?

**Comment by ds-ga-1007** [comment]
Merged.

**Pull request merged**
