### PR TITLE
Assignment5_Zhiqi_Guo(zg475)

### PR DESCRIPTION
**Pull request by guozhiqi14**
Zhiqi Guo
zg475

### CODE REVIEW

**Comment by ds-ga-1007** [comment]
I am just letting you know that your repo has conflicts.
Conflicting files: adventure/tests/test_walks.py

**Comment by guozhiqi14** [comment]
Hi, I'm not pretty sure why the test_walks.py has a conflict, all I did is uncomment the last two tests.

**Comment by ds-ga-1007** [comment]
Conflicting files
adventure/adventure.py

**Comment by ds-ga-1007** [comment]
Conflicting files
adventure/adventure.py

Still a conflict

**Comment by guozhiqi14** [comment]
Coule that be more specific?

**Comment by ds-ga-1007** [comment]
Normally, you could try to remove that file. Have you tried?

**Comment by guozhiqi14** [comment]
Im not pretty sure why am getting a conflict since for adventure.py I only changed raw_input() to input().
Are you saying delete the whole adventure folder or adventure.py file? and re-push to my Github?

**Comment by ds-ga-1007** [comment]
Just try to delete one file.

**Comment by guozhiqi14** [comment]
Just deleted the adventure.py, hopefully that will work

**Comment by ds-ga-1007** [comment]
Sorry. Still cannot merge yours. Please check with professor with your question. Maybe some screenshots.

**Pull request closed without merging**
