### PR TITLE
ws854 assignment5 submission 

### PR DESCRIPTION
**Pull request by ws854**

### CODE REVIEW

**Comment by ds-ga-1007** [comment]
I am just letting you know that your repo has conflicts.
Conflicting files: adventure/tests/test_walks.py

**Comment by ws854** [comment]
Can I resubmit the pull request? I am not too sure why it results a conflict though..

**Comment by ds-ga-1007** [comment]
As long as you have submitted in time. I will allow you resubmit until you solved it, but do not take too long.

**Comment by ds-ga-1007** [comment]
I still see the same issue. Take your time and fix it.

**Comment by ws854** [comment]
Thank you! I am still working this now and will let you know once i finish fixing the issue. Thanks again for allowing me fix the conflict.

**Comment by ws854** [comment]
I think the conflict has been fixed. Please let me know if you are able to merge the pull request this time. Thanks!!

**Pull request merged**
